apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_TYPE
          value: "h2"
        - name: MB_DB_FILE
          value: "/metabase-data/metabase.db"
        volumeMounts:
        - name: metabase-storage
          mountPath: /metabase-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: metabase-storage
        persistentVolumeClaim:
          claimName: metabase-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: default
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
